### PR TITLE
Update anomalies guide

### LINKED ISSUE #17: Update clusters documentation  as we deploy the new version
We are developing models by applications and we should update the documentation accordingly.

### PR DESCRIPTION
**Pull request by allanino**
This contains updated GIFs for the Transaction Patterns guide plus some updates on the new chart layout and a brand new page with advanced settings explanation.

This closes #17.

**Trello card:** https://trello.com/c/d8EkaEXN/64-2-update-ai-clusters-documentation

### CODE REVIEW

**Comment by allanino** [comment]
I'm not sure about who can review this, so I haven't assigned it to anyone yet. Maybe @davidtkelleher is up to the task?

**Comment by davidtkelleher** [comment]
Hey, sure @allanino I'll take this one. Is there an urgency or can be in the next day or two?

**Comment by allanino** [comment]
Thanks, @davidtkelleher! There's no urgency. Issue #17 was opened on Nov 26, 2014, so I think two more days is alright.

**Comment by davidtkelleher** [comment]
Haha!! Ok then @allanino (I should have referred to the issue firstly ;) ) Yes, two days are more will be fine then, thanks.

**Comment by davidtkelleher** [comment]
Hey @allanino I reviewed your changes and made some further changes.. is this the correct workflow or should I just have focused on your changes only, as part of this PR? 
Let's talk more about it in the morning. In the meantime, please feel free to review the additional changes I have included here. Thanks.

**Comment by allanino** [comment]
Hey @david, I just added an item for advanced settings on the overview list. I also updated the `pt-BR` file to be consistent with the `en` one.

**Comment by davidtkelleher** [comment]
looks good to me @allanino I'll merge this now :+1:

**Pull request merged**
