### PR TITLE
Setup guide d200

### PR DESCRIPTION
**Pull request by gabrielbernal**
Implemented the D200 setup guide page, one page to guide the user to load the framework using Term Assist on windows, and the other to load the framework using Linux, with the command line tool XCB.

### CODE REVIEW

**Comment by davidtkelleher** [comment]
Hey @gabrielbernal do we know what's happening with this PR? It's been here for 3 months already.

**Comment by bmsatierf** [comment]
@davidtkelleher it wasn't merged because we haven't deployed the Ruby environment yet.

**Comment by davidtkelleher** [comment]
@bmsatierf ok! makes sense, thanks man ;)

**Comment by bmsatierf** [comment]
Merged on branch `ruby-release`! Thanks @gabrielbernal

**Pull request closed without merging**
