### PR TITLE
POSXML review

### PR DESCRIPTION
**Pull request by davidtkelleher**
This is the final commit of this review, totalling 133/133 reviews completed.

Reviewed and fixed EN content and replaced POSXML HTML with public Gists.

Removed file for command <input.getvalue> as it is not required.

Performed a complete translation from PT-BR to EN for the tables listed in <emv.getinfo> and <emv.adddate>

### CODE REVIEW

**Comment by davidtkelleher** [comment]
@bmsatierf of course, I'll just figure that out first and then move. Thanks.

**Comment by bmsatierf** [comment]
@davidtkelleher okay, please let me know if you need help.

Also, you can use this file as an example:

https://github.com/cloudwalkio/cloudwalk-docs/blob/master/templates/posxml/commands/emv.cleanstructures.erb

**Comment by davidtkelleher** [comment]
@bmsatierf perfect, will do. Thanks.

**Comment by davidtkelleher** [comment]
@bmsatierf I'm not sure if you saw, but I committed the internationalisation changes yesterday. thanks.

**Pull request merged**
