### PR TITLE
Posxml function

### PR DESCRIPTION
**Pull request by bmsatierf**
@davidtkelleher hey man, can you please review?

### CODE REVIEW

**Comment by posxml** [comment]
Hey @williamrgt I tried running this function in the IDE, but it crashed. Can you check it out please?

https://gist.github.com/posxml/326fe290e2c236338a9e

Also, could you added *commented* outputs for each section of the function, for testing and demo purposes? Thanks.

**Comment by williamrgt** [comment]
@davidtkelleher Hey man. So, Where's the error? because I compiled the code on the IDE and It worked fine, look:
screen shot 2015-11-09 at 9 26 24 pm

**Comment by posxml** [comment]
@williamrgt there's no error. When I try to emulate the code, the browser hands and eventually crashes.

**Comment by posxml** [comment]
@williamrgt the browser *hangs*

**Comment by williamrgt** [comment]
@davidtkelleher Hey man, could you test it again? https://ide.cloudwalk.io/dc4236e83a2f4ea58b561e3348f897aa.posxml?app_id=339

**Comment by davidtkelleher** [comment]
@williamrgt perfect, thanks William.. merging.

**Pull request merged**
